import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Navbar from './ui/navbar'
import { getCategories } from '@/actions/get-categories'
import FloatButton from './ui/float-button/float-button'
import { Toaster } from 'sonner'
import Footer from './ui/footer/footer'
import { getGlobal } from '@/actions/get-global'
import { Facebook, Instagram, PhoneCall, Send as Telegram } from 'lucide-react'
import { WhatsAppIcon } from './ui/icons/whatsapp-icon'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const categories = await getCategories()
  const { data } = await getGlobal()

  const socialLinks = [
    {
      name: 'Facebook',
      href: data.facebook,
      icon: <Facebook size={20} />,
      color: '#1877F2'
    },
    {
      name: 'Instagram',
      href: data.instagram,
      icon: <Instagram size={20} />,
      color: '#E4405F'
    },
    {
      name: 'Telegram',
      href: data.telegram,
      icon: <Telegram size={20} />,
      color: '#26A5E4'
    },
    {
      name: 'WhatsApp',
      href: data.whatsapp,
      icon: <WhatsAppIcon size={20} />,
      color: '#25D366'
    },
    {
      name: 'Call',
      href: 'tel:' + data.phoneNumber,
      icon: <PhoneCall size={20} />,
      color: '#34b7f1'
    }
  ]

  return (
    <html
      lang='en'
      className='h-full'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-full`}>
        <main className='flex-1 h-full'>
          <Navbar
            categories={categories.data}
            email={data.email}
            facebook={data.facebook}
            instagram={data.instagram}
            phoneNumber={`${data.phoneNumber}`}
            telegram={data.telegram}
            whatsapp={data.whatsapp}
          />
          {children}
          <FloatButton socialLinks={socialLinks} />
          <Toaster />
        </main>
        <Footer />
      </body>
    </html>
  )
}
